### ISSUE TITLE
The provided weight maybe wrong

### ISSUE THREAD

**Issue by sontung2310** [willyfh/clip4caption#1]
Hi, I have tried your provided checkpoints and the result of **CLIP4Caption (ViT-B/32)** is same as your benchmark, but **CLIP4Caption (ViT-B/16)** version is much different. Here is the result that I have evaluated:

![image](https://user-images.githubusercontent.com/62052338/210914154-ba356acb-c7f9-4bc8-9d10-85d7228eef14.png)
_CLIP4Caption (ViT-B/32) version_

![image](https://user-images.githubusercontent.com/62052338/210914271-0ea595de-6ce8-4d7b-9e28-18062a7c1f12.png)
_CLIP4Caption (ViT-B/16) version_

Thank you very much. Have a good day!

**Comment by sontung2310** [comment]
Hi, I have tried your provided checkpoints and the result of **CLIP4Caption (ViT-B/32)** is same as your benchmark, but **CLIP4Caption (ViT-B/16)** version is much different. Here is the result that I have evaluated:

![image](https://user-images.githubusercontent.com/62052338/210914154-ba356acb-c7f9-4bc8-9d10-85d7228eef14.png)
_CLIP4Caption (ViT-B/32) version_

![image](https://user-images.githubusercontent.com/62052338/210914271-0ea595de-6ce8-4d7b-9e28-18062a7c1f12.png)
_CLIP4Caption (ViT-B/16) version_

**Comment by willyfh** [comment]
Thank you for checking. I have reconfirmed again using the uploaded the checkpoint, and this is the result:
![image](https://user-images.githubusercontent.com/5786636/211124488-e078669c-5491-42f2-92ba-6c59e4f0ac81.png)

FYI, the provided CLIP4Clip features were extracted from the one pre-trained with ViT-B/32. If you want to try the pre-trained CLIP4Caption (ViT-B/16), you need to first prepare the CLIP4Clip (ViT-B/16) features by following [this instruction](https://github.com/willyfh/clip4caption/tree/main/feature_extractor).

Or I will also provide the extracted features for the ViT-B/16 later.

**Comment by sontung2310** [comment]
Thank you for replying. I forgot to change the extract features pre-trained from ViT-B/32 to ViT-B/16 :) 

Have a good day!
